### GET request to example server
@host= 192.168.0.115
@port = 8111
@user= admin
@password= admin

### Hardcoded test data
@projectId = test_project_2
@buildTypeId = test_build_type_2

###GET all projects
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json
###

### 1. Create project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/projects
Content-Type: application/json
Accept: application/json

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "{{projectId}}",
  "id": "{{projectId}}",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
  "id": "{{buildTypeId}}",
  "name": "Print hello world",
  "project": {
    "id": "{{projectId}}"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
  "buildType": {
    "id": "{{buildTypeId}}"
  }
}

###GET project by id
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects/id:{{projectId}}
Content-Type: application/json
Accept: application/json
###